# http://www.appveyor.com/docs/appveyor-yml

# Set build version format here instead of in the admin panel
version: "{build}"

# Do not build on gh tags
skip_tags: true

# Test against these versions of Node.js
environment:

  matrix:
    # Node versions to run
    - nodejs_version: 7

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# Install scripts--runs after repo cloning
install:
  # Install chrome
  - choco install -y googlechrome
  # Install the latest stable version of Node
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

# Disable automatic builds
build: off

# Post-install test scripts
test_script:
  # Output debugging info
  - node --version
  - npm --version
  # run build and run tests
  - npm run build

# Cache node_modules for faster builds
cache:
  - node_modules -> package.json

notifications:
  - provider: Slack
    incoming_webhook:
      secure: MSqsDPNe8vFbSUgpanQssNkxPI/5bsVOV2QX4Xg5XZ6vfVKoWBwzZ+4WXGdgjw5hbVihM9OC8jfBtuzxzr+UZ/xvI+u2ITM1IyocX4tUfL4=
    on_build_success: true
    on_build_failure: true
